// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"openapi"
	"openapi/internal/utils"
	"openapi/models/components"
	"testing"
)

func TestUser_CreateUser(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("createUser")

	s := openapi.New(
		openapi.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		openapi.WithClient(testHTTPClient),
		openapi.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.User.CreateUser(ctx, &components.User{
		ID:         openapi.Int64(10),
		Username:   openapi.String("theUser"),
		FirstName:  openapi.String("John"),
		LastName:   openapi.String("James"),
		Email:      openapi.String("john@email.com"),
		Password:   openapi.String("12345"),
		Phone:      openapi.String("12345"),
		UserStatus: openapi.Int(1),
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.User)
	assert.Equal(t, &components.User{
		ID:         openapi.Int64(10),
		Username:   openapi.String("theUser"),
		FirstName:  openapi.String("John"),
		LastName:   openapi.String("James"),
		Email:      openapi.String("john@email.com"),
		Password:   openapi.String("12345"),
		Phone:      openapi.String("12345"),
		UserStatus: openapi.Int(1),
	}, res.User)

}

func TestUser_CreateUsersWithListInput(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("createUsersWithListInput")

	s := openapi.New(
		openapi.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		openapi.WithClient(testHTTPClient),
		openapi.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.User.CreateUsersWithListInput(ctx, []components.User{
		components.User{
			ID:         openapi.Int64(10),
			Username:   openapi.String("theUser"),
			FirstName:  openapi.String("John"),
			LastName:   openapi.String("James"),
			Email:      openapi.String("john@email.com"),
			Password:   openapi.String("12345"),
			Phone:      openapi.String("12345"),
			UserStatus: openapi.Int(1),
		},
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.User)
	assert.Equal(t, &components.User{
		ID:         openapi.Int64(10),
		Username:   openapi.String("theUser"),
		FirstName:  openapi.String("John"),
		LastName:   openapi.String("James"),
		Email:      openapi.String("john@email.com"),
		Password:   openapi.String("12345"),
		Phone:      openapi.String("12345"),
		UserStatus: openapi.Int(1),
	}, res.User)

}

func TestUser_LoginUser(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("loginUser")

	s := openapi.New(
		openapi.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		openapi.WithClient(testHTTPClient),
		openapi.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.User.LoginUser(ctx, nil, nil)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.String)
	assert.Equal(t, openapi.String("<value>"), res.String)

}

func TestUser_LogoutUser(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("logoutUser")

	s := openapi.New(
		openapi.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		openapi.WithClient(testHTTPClient),
		openapi.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.User.LogoutUser(ctx)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}

func TestUser_GetUserByName(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getUserByName")

	s := openapi.New(
		openapi.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		openapi.WithClient(testHTTPClient),
		openapi.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.User.GetUserByName(ctx, "Zachery_Lubowitz15")
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.User)
	assert.Equal(t, &components.User{
		ID:         openapi.Int64(10),
		Username:   openapi.String("theUser"),
		FirstName:  openapi.String("John"),
		LastName:   openapi.String("James"),
		Email:      openapi.String("john@email.com"),
		Password:   openapi.String("12345"),
		Phone:      openapi.String("12345"),
		UserStatus: openapi.Int(1),
	}, res.User)

}

func TestUser_UpdateUser(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("updateUser")

	s := openapi.New(
		openapi.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		openapi.WithClient(testHTTPClient),
		openapi.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.User.UpdateUser(ctx, "Dandre_Hand41", &components.User{
		ID:         openapi.Int64(10),
		Username:   openapi.String("theUser"),
		FirstName:  openapi.String("John"),
		LastName:   openapi.String("James"),
		Email:      openapi.String("john@email.com"),
		Password:   openapi.String("12345"),
		Phone:      openapi.String("12345"),
		UserStatus: openapi.Int(1),
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}

func TestUser_DeleteUser(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("deleteUser")

	s := openapi.New(
		openapi.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		openapi.WithClient(testHTTPClient),
		openapi.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.User.DeleteUser(ctx, "Demetris_Schmitt")
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.User)
	assert.Equal(t, &components.User{
		ID:         openapi.Int64(10),
		Username:   openapi.String("theUser"),
		FirstName:  openapi.String("John"),
		LastName:   openapi.String("James"),
		Email:      openapi.String("john@email.com"),
		Password:   openapi.String("12345"),
		Phone:      openapi.String("12345"),
		UserStatus: openapi.Int(1),
	}, res.User)

}
