workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    petstore-oas:
        inputs:
            - location: openapi.json
        registry:
            location: registry.speakeasyapi.dev/ryan-local/ryan-testing-demo/petstore-oas
targets:
    petstore:
        target: go
        source: petstore-oas
        output: .
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/ryan-local/ryan-testing-demo/petstore-oas-go-code-samples
            blocking: false
        testing:
            enabled: true
