name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
      set_version:
        description: optionally set a specific SDK version
        type: string
  schedule:
    - cron: 0 0 * * *
  pull_request:
    types: [labeled, unlabeled]
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15.39.0
    with:
      force: ${{ github.event.inputs.force }}
      mode: pr
      set_version: ${{ github.event.inputs.set_version }}
      target: petstore
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
  test-petstore:
    needs: generate  # Ensures 'test-petstore' runs AFTER 'generate'
    uses: ryan-timothy-albert/simple-go-sdk/.github/workflows/sdk_test.yaml@speakeasy-sdk-regen-1738792290  # Replace with correct branch
    with:
      target: petstore
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}  # Pass explicitly
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}  # Pass explicitly
