name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
      set_version:
        description: Optionally set a specific SDK version
        type: string
  schedule:
    - cron: 0 0 * * *
  pull_request:
    types: [labeled, unlabeled]

jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15.39.0
    with:
      force: ${{ github.event.inputs.force }}
      mode: pr
      set_version: ${{ github.event.inputs.set_version }}
      target: petstore
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}  # ✅ Must be explicitly passed
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}

  dispatch-sdk-test:
    needs: generate  # Ensures 'dispatch-sdk-test' runs AFTER 'generate'
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch SDK Test Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "ref": "speakeasy-sdk-regen-1738792290",
              "inputs": {
                "target": "petstore"
              }
            }' \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/sdk-test.yaml/dispatches"
