name: Test Petstore
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
"on":
  workflow_dispatch:
    inputs:
      target:
        description: Specific target to test
        type: string
  pull_request:
    paths:
      - .speakeasy/gen.lock
    branches:
      - main
  workflow_call:
    inputs:
      target:
        description: Specific target to test
        required: true
        type: string
    secrets:
      github_access_token:
        required: true
      speakeasy_api_key:
        required: true
jobs:
  test:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-test.yaml@v15.39.0
    with:
      target: ${{ github.event.inputs.target }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
